export const exerciseLibrary = [
  { id: 'supino-reto', name: 'Supino Reto', muscle: 'Peito', equipment: 'Barra', fig: 'supino', defaultSets: 4, defaultReps: '10', description: 'Deite no banco, segure a barra na largura dos ombros. Desça controlado até o peito e empurre pra cima.' },
  { id: 'supino-inclinado', name: 'Supino Inclinado', muscle: 'Peito', equipment: 'Barra', fig: 'supino', defaultSets: 3, defaultReps: '12', description: 'Banco inclinado 30-45°. Trabalha mais a porção superior do peito.' },
  { id: 'supino-declinado', name: 'Supino Declinado', muscle: 'Peito', equipment: 'Barra', fig: 'supino', defaultSets: 3, defaultReps: '12', description: 'Banco declinado. Foca a porção inferior do peito.' },
  { id: 'supino-halteres', name: 'Supino com Halteres', muscle: 'Peito', equipment: 'Halteres', fig: 'supino', defaultSets: 3, defaultReps: '12', description: 'Amplitude maior que com barra.' },
  { id: 'crucifixo', name: 'Crucifixo', muscle: 'Peito', equipment: 'Halteres', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Braços levemente flexionados. Abra em arco até sentir alongamento.' },
  { id: 'crossover', name: 'Crossover na Polia', muscle: 'Peito', equipment: 'Polia', fig: 'puxada', defaultSets: 3, defaultReps: '15', description: 'Polias altas. Traga as mãos em direção ao centro do corpo.' },
  { id: 'mergulho', name: 'Mergulho (Dips)', muscle: 'Peito', equipment: 'Paralelas', fig: 'agacha', defaultSets: 3, defaultReps: '10', description: 'Incline o tronco pra frente pra focar mais peito.' },
  { id: 'peck-deck', name: 'Peck Deck (Voador)', muscle: 'Peito', equipment: 'Máquina', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Aperte os braços contra os apoios sem usar impulso.' },
  { id: 'puxada-alta', name: 'Puxada Alta', muscle: 'Costas', equipment: 'Polia', fig: 'puxada', defaultSets: 4, defaultReps: '10', description: 'Pegada larga, puxe a barra até a altura do queixo.' },
  { id: 'puxada-pegada-fechada', name: 'Puxada Pegada Fechada', muscle: 'Costas', equipment: 'Polia', fig: 'puxada', defaultSets: 3, defaultReps: '12', description: 'Pegada neutra ou supinada. Foca mais a parte inferior das costas.' },
  { id: 'remada-curvada', name: 'Remada Curvada', muscle: 'Costas', equipment: 'Barra', fig: 'puxada', defaultSets: 3, defaultReps: '12', description: 'Tronco a 45°, puxe a barra em direção ao umbigo.' },
  { id: 'remada-sentada', name: 'Remada Sentada', muscle: 'Costas', equipment: 'Polia', fig: 'puxada', defaultSets: 3, defaultReps: '12', description: 'Costas retas, puxe o triângulo até o abdômen.' },
  { id: 'remada-cavalinho', name: 'Remada Cavalinho (T-Bar)', muscle: 'Costas', equipment: 'Barra T', fig: 'puxada', defaultSets: 3, defaultReps: '10', description: 'Pegada neutra na barra. Puxe contra o abdômen.' },
  { id: 'remada-unilateral', name: 'Remada Unilateral (Serrote)', muscle: 'Costas', equipment: 'Halter', fig: 'puxada', defaultSets: 3, defaultReps: '12', description: 'Apoie joelho e mão no banco. Puxe o halter até a lateral do tronco.' },
  { id: 'pulldown', name: 'Pulldown com Braços Retos', muscle: 'Costas', equipment: 'Polia', fig: 'puxada', defaultSets: 3, defaultReps: '15', description: 'Braços estendidos, traga a barra até as coxas.' },
  { id: 'levantamento-terra', name: 'Levantamento Terra', muscle: 'Costas', equipment: 'Barra', fig: 'agacha', defaultSets: 4, defaultReps: '8', description: 'Composto pesado. Costas retas, quadril desce.' },
  { id: 'pull-up', name: 'Barra Fixa', muscle: 'Costas', equipment: 'Barra Fixa', fig: 'puxada', defaultSets: 4, defaultReps: '8', description: 'Pegada pronada, suba até o queixo passar da barra.' },
  { id: 'agachamento-livre', name: 'Agachamento Livre', muscle: 'Pernas', equipment: 'Barra', fig: 'agacha', defaultSets: 4, defaultReps: '10', description: 'Rei dos exercícios. Pés na largura dos ombros.' },
  { id: 'agachamento-frontal', name: 'Agachamento Frontal', muscle: 'Pernas', equipment: 'Barra', fig: 'agacha', defaultSets: 3, defaultReps: '10', description: 'Barra apoiada na clavícula. Mais focado em quadríceps.' },
  { id: 'leg-press', name: 'Leg Press', muscle: 'Pernas', equipment: 'Máquina', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Pés na altura média do apoio. Desça até os joelhos formarem 90°.' },
  { id: 'hack-squat', name: 'Hack Squat', muscle: 'Pernas', equipment: 'Máquina', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Máquina com apoio nas costas. Foca quadríceps.' },
  { id: 'cadeira-extensora', name: 'Cadeira Extensora', muscle: 'Pernas', equipment: 'Máquina', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Isolado de quadríceps.' },
  { id: 'avanco', name: 'Avanço (Afundo)', muscle: 'Pernas', equipment: 'Halteres', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Passo à frente, desce até os dois joelhos formarem 90°.' },
  { id: 'sissy-squat', name: 'Sissy Squat', muscle: 'Pernas', equipment: 'Corpo livre', fig: 'agacha', defaultSets: 3, defaultReps: '15', description: 'Avançado. Joelhos vão pra frente enquanto tronco inclina pra trás.' },
  { id: 'stiff', name: 'Stiff', muscle: 'Pernas', equipment: 'Barra', fig: 'agacha', defaultSets: 3, defaultReps: '10', description: 'Pernas semi-rígidas, desça a barra até sentir alongamento no posterior.' },
  { id: 'mesa-flexora', name: 'Mesa Flexora', muscle: 'Pernas', equipment: 'Máquina', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Deitado, flexione os joelhos contraindo o posterior.' },
  { id: 'cadeira-flexora', name: 'Cadeira Flexora Sentada', muscle: 'Pernas', equipment: 'Máquina', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Sentado, flexione os joelhos.' },
  { id: 'good-morning', name: 'Good Morning', muscle: 'Pernas', equipment: 'Barra', fig: 'agacha', defaultSets: 3, defaultReps: '10', description: 'Barra nas costas, incline o tronco pra frente mantendo costas retas.' },
  { id: 'panturrilha-pe', name: 'Panturrilha em Pé', muscle: 'Pernas', equipment: 'Máquina', fig: 'agacha', defaultSets: 4, defaultReps: '15', description: 'Suba na ponta dos pés o máximo possível.' },
  { id: 'panturrilha-sentado', name: 'Panturrilha Sentado', muscle: 'Pernas', equipment: 'Máquina', fig: 'agacha', defaultSets: 4, defaultReps: '15', description: 'Foca o sóleo. Joelhos a 90°.' },
  { id: 'desenvolvimento', name: 'Desenvolvimento Militar', muscle: 'Ombro', equipment: 'Barra', fig: 'desen', defaultSets: 4, defaultReps: '10', description: 'Barra na altura dos ombros, empurre acima da cabeça.' },
  { id: 'desenvolvimento-halteres', name: 'Desenvolvimento com Halteres', muscle: 'Ombro', equipment: 'Halteres', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Sentado ou em pé. Mais natural que com barra.' },
  { id: 'arnold-press', name: 'Arnold Press', muscle: 'Ombro', equipment: 'Halteres', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Halteres começam com palmas pra dentro.' },
  { id: 'elevacao-lateral', name: 'Elevação Lateral', muscle: 'Ombro', equipment: 'Halteres', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Levante os halteres lateralmente até a altura dos ombros.' },
  { id: 'elevacao-frontal', name: 'Elevação Frontal', muscle: 'Ombro', equipment: 'Halteres', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Levante os halteres à frente até a altura dos ombros.' },
  { id: 'crucifixo-inverso', name: 'Crucifixo Inverso', muscle: 'Ombro', equipment: 'Halteres', fig: 'desen', defaultSets: 3, defaultReps: '15', description: 'Tronco inclinado, abra os braços lateralmente.' },
  { id: 'encolhimento', name: 'Encolhimento (Shrug)', muscle: 'Ombro', equipment: 'Halteres', fig: 'desen', defaultSets: 3, defaultReps: '15', description: 'Eleve os ombros em direção às orelhas.' },
  { id: 'rosca-direta', name: 'Rosca Direta', muscle: 'Bíceps', equipment: 'Barra', fig: 'rosca', defaultSets: 4, defaultReps: '10', description: 'Cotovelos fixos ao lado do corpo. Suba a barra até a altura do peito.' },
  { id: 'rosca-martelo', name: 'Rosca Martelo', muscle: 'Bíceps', equipment: 'Halteres', fig: 'rosca', defaultSets: 3, defaultReps: '12', description: 'Pegada neutra (martelo).' },
  { id: 'rosca-alternada', name: 'Rosca Alternada', muscle: 'Bíceps', equipment: 'Halteres', fig: 'rosca', defaultSets: 3, defaultReps: '12', description: 'Halteres, um braço de cada vez.' },
  { id: 'rosca-concentrada', name: 'Rosca Concentrada', muscle: 'Bíceps', equipment: 'Halter', fig: 'rosca', defaultSets: 3, defaultReps: '10', description: 'Cotovelo apoiado na coxa interna.' },
  { id: 'rosca-scott', name: 'Rosca Scott', muscle: 'Bíceps', equipment: 'Barra W', fig: 'rosca', defaultSets: 3, defaultReps: '12', description: 'Banco Scott, cotovelos fixos no apoio.' },
  { id: 'triceps-pulley', name: 'Tríceps Pulley', muscle: 'Tríceps', equipment: 'Polia', fig: 'puxada', defaultSets: 4, defaultReps: '10', description: 'Cotovelos fixos ao lado do corpo.' },
  { id: 'triceps-testa', name: 'Tríceps Testa', muscle: 'Tríceps', equipment: 'Barra W', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Deitado, barra desce em direção à testa.' },
  { id: 'triceps-frances', name: 'Tríceps Francês', muscle: 'Tríceps', equipment: 'Halter', fig: 'desen', defaultSets: 3, defaultReps: '12', description: 'Halter atrás da cabeça, com as duas mãos.' },
  { id: 'triceps-corda', name: 'Tríceps Corda', muscle: 'Tríceps', equipment: 'Polia', fig: 'puxada', defaultSets: 3, defaultReps: '12', description: 'Corda na polia alta.' },
  { id: 'triceps-mergulho-banco', name: 'Mergulho no Banco', muscle: 'Tríceps', equipment: 'Banco', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Mãos apoiadas no banco atrás.' },
  { id: 'abdominal-reto', name: 'Abdominal Reto', muscle: 'Abdômen', equipment: 'Corpo livre', fig: 'abdo', defaultSets: 3, defaultReps: '20', description: 'Deitado, suba o tronco contraindo o abdômen.' },
  { id: 'prancha', name: 'Prancha', muscle: 'Abdômen', equipment: 'Corpo livre', fig: 'abdo', defaultSets: 3, defaultReps: '30s', description: 'Isométrico. Apoie nos antebraços.' },
  { id: 'abdominal-infra', name: 'Abdominal Infra (Pernas)', muscle: 'Abdômen', equipment: 'Corpo livre', fig: 'abdo', defaultSets: 3, defaultReps: '15', description: 'Deitado, eleve as pernas em direção ao peito.' },
  { id: 'abdominal-oblique', name: 'Abdominal Oblíquo', muscle: 'Abdômen', equipment: 'Corpo livre', fig: 'abdo', defaultSets: 3, defaultReps: '15', description: 'Suba o tronco torcendo, cotovelo em direção ao joelho oposto.' },
  { id: 'abdominal-bicicleta', name: 'Abdominal Bicicleta', muscle: 'Abdômen', equipment: 'Corpo livre', fig: 'abdo', defaultSets: 3, defaultReps: '20', description: 'Pedalando no ar, encoste cotovelo no joelho oposto alternadamente.' },
  { id: 'prancha-lateral', name: 'Prancha Lateral', muscle: 'Abdômen', equipment: 'Corpo livre', fig: 'abdo', defaultSets: 3, defaultReps: '30s', description: 'Apoie num antebraço só, corpo de lado.' },
  { id: 'rosca-punho', name: 'Rosca de Punho', muscle: 'Antebraço', equipment: 'Barra', fig: 'rosca', defaultSets: 3, defaultReps: '15', description: 'Antebraços apoiados, só os punhos saem do apoio.' },
  { id: 'rosca-inversa', name: 'Rosca Inversa', muscle: 'Antebraço', equipment: 'Barra', fig: 'rosca', defaultSets: 3, defaultReps: '12', description: 'Pegada pronada (palmas pra baixo).' },
  { id: 'hip-thrust', name: 'Hip Thrust', muscle: 'Glúteo', equipment: 'Barra', fig: 'agacha', defaultSets: 4, defaultReps: '12', description: 'Costas no banco, barra no quadril.' },
  { id: 'elevacao-pelvica', name: 'Elevação Pélvica', muscle: 'Glúteo', equipment: 'Corpo livre', fig: 'agacha', defaultSets: 3, defaultReps: '15', description: 'Deitado, pés no chão. Eleve o quadril contraindo o glúteo.' },
  { id: 'coice-polia', name: 'Coice na Polia (Glúteo)', muscle: 'Glúteo', equipment: 'Polia', fig: 'agacha', defaultSets: 3, defaultReps: '12', description: 'Tornozeleira na polia baixa.' },
  { id: 'abducao', name: 'Abdução de Quadril', muscle: 'Glúteo', equipment: 'Máquina', fig: 'agacha', defaultSets: 3, defaultReps: '15', description: 'Máquina específica.' },
  { id: 'esteira', name: 'Esteira (Caminhada/Corrida)', muscle: 'Cardio', equipment: 'Esteira', fig: 'agacha', defaultSets: 1, defaultReps: '20min', description: 'Aquecimento ou cardio principal.' },
  { id: 'bike', name: 'Bicicleta Ergométrica', muscle: 'Cardio', equipment: 'Bike', fig: 'agacha', defaultSets: 1, defaultReps: '20min', description: 'Cardio sem impacto.' },
  { id: 'eliptico', name: 'Elíptico', muscle: 'Cardio', equipment: 'Elíptico', fig: 'desen', defaultSets: 1, defaultReps: '20min', description: 'Cardio sem impacto que envolve membros superiores.' },
  { id: 'hiit', name: 'HIIT', muscle: 'Cardio', equipment: 'Variado', fig: 'agacha', defaultSets: 8, defaultReps: '30s', description: 'Treino intervalado de alta intensidade.' },
];

export const muscleGroups = ['Todos', 'Peito', 'Costas', 'Pernas', 'Ombro', 'Bíceps', 'Tríceps', 'Abdômen', 'Antebraço', 'Glúteo', 'Cardio'];
